
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 833958086342-8qnk6sqc3vqhkbmnsnjpv67qslcnv7a9.apps.googleusercontent.com
                        client-secret: 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
                        scope: openid,profile,email

                    naver:
                        client-id: PyqTi2mMDkpj2i9Y22z4
                        client-secret: kSKrKX7XYO
                        authorization-grant-type: authorization_code
                        client-name: re100Naver
                        redirect-uri: http://localhost:8081/login/oauth2/code/naver
                        scope: profile,email

                    kakao:
                        client-id: 7899e32aab9c80cf91b091578721da0f
                        client-secret: lhDywbjR8YNQWhyZxkUz991KrbW33g5v
                        authorization-grant-type: authorization_code
#                        client-authentication-method: POST # 안됨
                        client-authentication-method: client_secret_post
#                        client-authentication-method: client_secret_basic
                        client-name: re100Kakao
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#                        redirect-uri: https://localhost:3000/login/oauth2/code/kakao
                        #                        scope: openid,profile_nickname,profile_image,account_email
                        scope: profile_nickname
#                        scope: profile_nickname,profile_image,account_email
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

                    kakao:
                    # OpenID Connect ? ?? jwkSet URI ? ???? ?? ??? ????
                        issuer-uri: https://kauth.kakao.com
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id # OpenID Connect ? ????? ???? ?? ??

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/coupon_db?characterEncoding=UTF-8&serverTimezone=UTC
        username: cire
        password: 1234
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
                show_sql: true

        defer-datasource-initialization: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql

    mvc:
        static-path-pattern: /static/**
        view:
            suffix: .html

logging:
    level:
        org:
            springframework:
                security: trace
server:
    servlet:
        session:
            cookie:
                same-site: none
                secure: true
    port: 8080
#    ssl:
#        key-store: keystore.p12
#        key-store-password: 123456
#        keyStoreType: PKCS12
#        keyAlias: tomcat

#server.servlet.session.cookie.secure=true